'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace TurnosMontagne

    Partial Public Class Turnos
        Inherits XPLiteObject
        Dim fidTurno As Integer
        <Key(True)>
        Public Property idTurno() As Integer
            Get
                Return fidTurno
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idTurno), fidTurno, value)
            End Set
        End Property
        Dim fNroLocal As Integer
        Public Property NroLocal() As Integer
            Get
                Return fNroLocal
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NroLocal), fNroLocal, value)
            End Set
        End Property
        Dim fFecha As String
        <Size(50)>
        Public Property Fecha() As String
            Get
                Return fFecha
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Fecha), fFecha, value)
            End Set
        End Property
        Dim fHorario As Integer
        Public Property Horario() As Integer
            Get
                Return fHorario
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Horario), fHorario, value)
            End Set
        End Property
        Dim fNroOrden As Integer
        Public Property NroOrden() As Integer
            Get
                Return fNroOrden
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NroOrden), fNroOrden, value)
            End Set
        End Property
        Dim fCliente As String
        <Size(50)>
        Public Property Cliente() As String
            Get
                Return fCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Cliente), fCliente, value)
            End Set
        End Property
        Dim fdniCliente As String
        <Size(20)>
        Public Property dniCliente() As String
            Get
                Return fdniCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(dniCliente), fdniCliente, value)
            End Set
        End Property
        Dim ftelCliente As String
        <Size(20)>
        Public Property telCliente() As String
            Get
                Return ftelCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(telCliente), ftelCliente, value)
            End Set
        End Property
        Dim fmailCliente As String
        <Size(50)>
        Public Property mailCliente() As String
            Get
                Return fmailCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(mailCliente), fmailCliente, value)
            End Set
        End Property
        Dim fCompro As String
        <Size(10)>
        Public Property Compro() As String
            Get
                Return fCompro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Compro), fCompro, value)
            End Set
        End Property
        Dim fObservaciones As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Observaciones() As String
            Get
                Return fObservaciones
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Observaciones), fObservaciones, value)
            End Set
        End Property
        Dim fReprogramo As String
        <Size(2)>
        Public Property Reprogramo() As String
            Get
                Return fReprogramo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Reprogramo), fReprogramo, value)
            End Set
        End Property

        Dim fNroTicket As Integer
        Public Property NroTicket() As Integer
            Get
                Return fNroTicket
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NroTicket), fNroTicket, value)
            End Set
        End Property
    End Class

End Namespace
