'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace TurnosMontagne

    Partial Public Class Usuarios
        Inherits XPLiteObject
        Dim fidUsuario As Integer
        <Key(True)>
        Public Property idUsuario() As Integer
            Get
                Return fidUsuario
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idUsuario), fidUsuario, value)
            End Set
        End Property
        Dim fUsuario As String
        <Size(20)>
        Public Property Usuario() As String
            Get
                Return fUsuario
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Usuario), fUsuario, value)
            End Set
        End Property
        Dim fClave As String
        <Size(20)>
        Public Property Clave() As String
            Get
                Return fClave
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Clave), fClave, value)
            End Set
        End Property
        Dim fNroLocal As Integer
        Public Property NroLocal() As Integer
            Get
                Return fNroLocal
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NroLocal), fNroLocal, value)
            End Set
        End Property
        Dim fHorario As String
        <Size(100)>
        Public Property Horario() As String
            Get
                Return fHorario
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Horario), fHorario, value)
            End Set
        End Property
        Dim fCupos As Integer
        Public Property Cupos() As Integer
            Get
                Return fCupos
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Cupos), fCupos, value)
            End Set
        End Property
        Dim fNombre As String
        <Size(50)>
        Public Property Nombre() As String
            Get
                Return fNombre
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Nombre), fNombre, value)
            End Set
        End Property

        Dim fTelLocal As String
        <Size(20)>
        Public Property TelLocal() As String
            Get
                Return fTelLocal
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(TelLocal), fTelLocal, value)
            End Set
        End Property
    End Class

End Namespace
