'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BdBarberia

    Partial Public Class Servicios
        Inherits XPLiteObject
        Dim fidServicio As Long
        <Key()>
        Public Property idServicio() As Long
            Get
                Return fidServicio
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)(NameOf(idServicio), fidServicio, value)
            End Set
        End Property
        Dim fDescripcion As String
        Public Property Descripcion() As String
            Get
                Return fDescripcion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Descripcion), fDescripcion, value)
            End Set
        End Property
        Dim fPrecio As Long
        Public Property Precio() As Long
            Get
                Return fPrecio
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)(NameOf(Precio), fPrecio, value)
            End Set
        End Property
    End Class

End Namespace
