'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BdBarberia

    Partial Public Class Turnos
        Inherits XPLiteObject
        Dim fidTurno As Long
        <Key()>
        Public Property idTurno() As Long
            Get
                Return fidTurno
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)(NameOf(idTurno), fidTurno, value)
            End Set
        End Property
        Dim fFecha As String
        <Size(50)>
        Public Property Fecha() As String
            Get
                Return fFecha
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Fecha), fFecha, value)
            End Set
        End Property
        Dim fHorario As Long
        Public Property Horario() As Long
            Get
                Return fHorario
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)(NameOf(Horario), fHorario, value)
            End Set
        End Property
        Dim fNroOrden As Long
        Public Property NroOrden() As Long
            Get
                Return fNroOrden
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)(NameOf(NroOrden), fNroOrden, value)
            End Set
        End Property
        Dim fCliente As String
        <Size(50)>
        Public Property Cliente() As String
            Get
                Return fCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Cliente), fCliente, value)
            End Set
        End Property
        Dim fdniCliente As String
        <Size(20)>
        Public Property dniCliente() As String
            Get
                Return fdniCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(dniCliente), fdniCliente, value)
            End Set
        End Property
        Dim ftelCliente As String
        <Size(20)>
        Public Property telCliente() As String
            Get
                Return ftelCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(telCliente), ftelCliente, value)
            End Set
        End Property
        Dim fmailCliente As String
        <Size(50)>
        Public Property mailCliente() As String
            Get
                Return fmailCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(mailCliente), fmailCliente, value)
            End Set
        End Property
        Dim fObservaciones As String
        Public Property Observaciones() As String
            Get
                Return fObservaciones
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Observaciones), fObservaciones, value)
            End Set
        End Property
        Dim fReprogramo As String
        <Size(2)>
        Public Property Reprogramo() As String
            Get
                Return fReprogramo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Reprogramo), fReprogramo, value)
            End Set
        End Property
        Dim fidBarbero As Long
        Public Property idBarbero() As Long
            Get
                Return fidBarbero
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)(NameOf(idBarbero), fidBarbero, value)
            End Set
        End Property
        Dim fidServicio As Long
        Public Property idServicio() As Long
            Get
                Return fidServicio
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)(NameOf(idServicio), fidServicio, value)
            End Set
        End Property
    End Class

End Namespace
