'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BdBarberia

    Partial Public Class Usuarios
        Inherits XPLiteObject
        Dim fidUsuario As Long
        <Key()>
        Public Property idUsuario() As Long
            Get
                Return fidUsuario
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)(NameOf(idUsuario), fidUsuario, value)
            End Set
        End Property
        Dim fNombre As String
        <Size(50)>
        Public Property Nombre() As String
            Get
                Return fNombre
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Nombre), fNombre, value)
            End Set
        End Property
        Dim fClave As String
        <Size(50)>
        Public Property Clave() As String
            Get
                Return fClave
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Clave), fClave, value)
            End Set
        End Property
        Dim fPermisos As String
        <Size(50)>
        Public Property Permisos() As String
            Get
                Return fPermisos
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Permisos), fPermisos, value)
            End Set
        End Property
    End Class

End Namespace
